service: serverless-cors

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
